services:
  backend:
    build:
      context: ./backend
    volumes:
      - ./backend:/app
      - ./storage:/app/storage
    ports:
      - "8000:8000"
    env_file:
      - .env
    depends_on:
      - db
    command: >
      sh -c "uvicorn app.main:app --reload --host 0.0.0.0 --port 8000 --app-dir src"

  frontend:
    build:
      context: ./frontend
    volumes:
      - ./frontend:/app
    ports:
      - "5173:5173"
    env_file:
      - .env
    command: >
      sh -c "npm run dev -- --host 0.0.0.0"

  db:
    image: postgres:15
    restart: unless-stopped
    env_file:
      - .env
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    networks:
      - postgres

  pgadmin:
    container_name: pgadmin
    image: dpage/pgadmin4:7.2
    env_file:
      - .env
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PG_EMAIL}
      PGADMIN_DEFAULT_PASSWORD: ${PG_PASS}
      PGADMIN_CONFIG_SERVER_MODE: 'True'
    volumes:
      - pgadmin_data:/var/lib/pgadmin
    ports:
      - "8080:8080"
    restart: unless-stopped
    networks:
      - postgres


volumes:
  postgres_data:
  pgadmin_data:

networks:
  postgres:
    driver: bridge