services:
  backend:
    container_name: be
    build:
      context: ./backend
    volumes:
      - ./backend:/app
      - ./storage:/app/storage
    expose:
      - "8000"
    env_file:
      - .env
    depends_on:
      - db
    networks:
      - web
    environment:
      - CORS_ALLOW_ORIGIN=https://flairbim.com

  frontend:
    container_name: fe
    build:
      context: ./frontend
    volumes:
      - ./frontend:/app
    ports:
      - "5173:5173"
    command: sh -c "npm run dev -- --host 0.0.0.0"
    env_file:
      - .env
    networks:
      - web

  db:
    image: postgres:15
    restart: unless-stopped
    env_file:
      - .env
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    networks:
      - web

  pgadmin:
    container_name: pgadmin
    image: dpage/pgadmin4
    env_file:
      - .env
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PG_EMAIL}
      PGADMIN_DEFAULT_PASSWORD: ${PG_PASS}
      PGADMIN_CONFIG_SERVER_MODE: 'True'
    volumes:
      - pgadmin_data:/var/lib/pgadmin
    ports:
      - "8080:8080"
    expose:
      - "8080"
    restart: unless-stopped
    networks:
      - web

  caddy:
    image: caddy:latest
    container_name: caddy
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./Caddyfile:/etc/caddy/Caddyfile
      - caddy_data:/data
      - caddy_config:/config
    networks:
      - web


volumes:
  postgres_data:
  pgadmin_data:
  caddy_data:
  caddy_config:

networks:
  web:
    driver: bridge