services:
  backend:
    build:
      context: ./backend
    volumes:
      - ./backend:/app
      - ./storage:/app/storage
    ports:
      - "8000:8000"
    env_file:
      - .env
    depends_on:
      - db
      - minio
    command: >
      sh -c "uvicorn app.main:app --reload --host 0.0.0.0 --port 8000 --app-dir src"

  frontend:
    build:
      context: ./frontend
    volumes:
      - ./frontend:/app
    ports:
      - "5173:5173"
    env_file:
      - .env
    command: >
      sh -c "npm run dev -- --host 0.0.0.0"

  db:
    image: postgres:15
    restart: unless-stopped
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  minio:
    image: minio/minio
    container_name: minio
    command: server /data --console-address ":9001"
    ports:
      - "9000:9000"
      - "9001:9001"
    volumes:
      - minio_data:/data
    environment:
      MINIO_ROOT_USER: ${S3_ACCESS_KEY}
      MINIO_ROOT_PASSWORD: ${S3_SECRET_KEY}
    restart: unless-stopped

  mc:
    image: minio/mc
    depends_on:
      - minio
    entrypoint: >
      /bin/sh -c "
        sleep 5;
        mc alias set local http://minio:9000 ${S3_ACCESS_KEY} ${S3_SECRET_KEY};
        mc mb -p local/${S3_BUCKET_NAME};
        mc policy set public local/${S3_BUCKET_NAME};
        exit 0;
      "

volumes:
  postgres_data:
  minio_data:
